# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/arm64/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

include $(call all-makefiles-under,$(LOCAL_PATH))

ifeq ($(TARGET_ARCH),arm64)

endif
